### ISSUE TITLE
Error after first run "in order to verify readjustments, please enable readjustments for all question types in the T&A administration"

### ISSUE THREAD

**Issue by rrbn** [lieblb/testilias#2]
Tested on ILIAS v5.3.5 2018-05-11.
Using test "TiltR.Demotest".
Error: Traceback (most recent call last):
  File "/tiltr/app/tiltr/driver/batch.py", line 802, in run
    raise e
  File "/tiltr/app/tiltr/driver/batch.py", line 792, in run
    self.prepare(master, test_driver)
  File "/tiltr/app/tiltr/driver/batch.py", line 539, in prepare
    master.report))
  File "/tiltr/app/tiltr/driver/drivers.py", line 274, in verify_admin_settings
    "in order to verify readjustments, please enable readjustments "
tiltr.data.exceptions.InteractionException: in order to verify readjustments, please enable readjustments for all question types in the T&A administration

Finished with status FAIL/interaction.

# LOG

[error] in order to verify readjustments, please enable readjustments for all question types in the T&A administration
[traceback] Traceback (most recent call last):
  File "/tiltr/app/tiltr/driver/batch.py", line 802, in run
    raise e
  File "/tiltr/app/tiltr/driver/batch.py", line 792, in run
    self.prepare(master, test_driver)
  File "/tiltr/app/tiltr/driver/batch.py", line 539, in prepare
    master.report))
  File "/tiltr/app/tiltr/driver/drivers.py", line 274, in verify_admin_settings
    "in order to verify readjustments, please enable readjustments "
tiltr.data.exceptions.InteractionException: in order to verify readjustments, please enable readjustments for all question types in the T&A administration

# PREFERENCES/WORKAROUNDS

sloppy_whitespace                      1
implicit_text_number_conversions       1
disallow_clamps_in_cloze               1
disallow_dollar_in_cloze               1
disallow_empty_answers                 1
random_xls_participant_sheet_orders    1
force_tinymce                          1
no_plaintext_longtext                  1
identical_scoring_ignores_comparator   1
disallow_invalid_answers               1
enable_autosave                        1
allow_empty_scores                     1
dont_readjust_kprim                    1
dont_readjust_matching                 0
no_remove_on_readjust_matching         1
allow_unreachable_max_scores           1

# PREFERENCES/SETTINGS

browser                            firefox  
resolution                         1024x1600
num_deterministic_machines         1        
crash_frequency                    1        
autosave_duration                  5        
autosave_tolerance                 10       
num_readjustments                  1        
modify_answer_frequency            50       
self_test_fake_error_level         0        
cloze_previous_answer_p            0.200    
cloze_text_enter_scored_p          0.750    
cloze_text_enter_random_number_p   0.100    
invalid_answer_p                   0.250    
test_passes                        AVR      
max_long_text_length               20       
max_cloze_text_length              7        
screenshot_refresh_time            10       
numbers_in_text_fields_p           0.050

**Comment by lieblb** [comment]
This should work out of the box, I need to update the packaged database to use other default settings.


As a workaround - until I fix this - you can do either of these things:

(1) go to the embedded ILIAS instance by clicking on the ILIAS string below the title logo and logging in  as "root" / "odysseus" to enable all readjustments:

![nachkorrektur-settings](https://user-images.githubusercontent.com/25431384/55951845-86cd7500-5c58-11e9-860f-3925bfb9642e.png)

(2) open the "settings" panel in TiltR and set readjustments to 0:

![Bildschirmfoto 2019-04-11 um 12 50 51](https://user-images.githubusercontent.com/25431384/55951908-a5cc0700-5c58-11e9-9541-6e1a85df035d.png)

**Comment by lieblb** [comment]
Fixed now. If you delete your db container and image (`docker rm tiltr_db_1`, `docker rmi tiltr_db`) and restart, things should work now.
